export enum HomeActions {
  SAVE_LIST_PRODUCT = "SAVE_LIST_PRODUCT",
  SAVE_LIST_CATEGORY = "SAVE_LIST_CATEGORY",
  SAVE_CART_DATA = "SAVE_CART_DATA",
  SAVE_ADDRESS_DATA = "SAVE_ADDRESS_DATA",
  SAVE_SELECTED_PRODUCTS = "SAVE_SELECTED_PRODUCT",
}

export enum AuthActions {
  TOAST_ERROR = "TOAST_ERROR",
  SAVE_ACCOUNT= "SAVE_ACCOUNT",
}

export enum SellerActions {
  CHANGE_SIDEBAR = "CHANGE_SIDEBAR",
  CHANGE_SUB_SIDEBAR = "CHANGE_SUB_SIDEBAR",
  CHANGE_VOUCHER = "CHANGE_VOUCHER",
  SAVE_LIST_PRODUCT = "SAVE_LIST_PRODUCT",
  SAVE_LIST_TRANSACTION = "SAVE_LIST_TRANSACTION",
  SAVE_LIST_VOUCHER = "SAVE_LIST_VOUCHER",
  SAVE_LIST_CATEGORY = "SAVE_LIST_CATEGORY",
  SAVE_LIST_PROFILE = "SAVE_LIST_PROFILE",
  SAVE_LIST_CHART = "SAVE_LIST_CHART",
  SAVE_LIST_CHART_FILTER_MONTH = "SAVE_LIST_CHART_FILTER_MONTH",
  SAVE_LIST_TRANSACTION_FILTER_MONTH = "SAVE_LIST_TRANSACTION_FILTER_MONTH",
}

