export const routes = {
  home: {
    Root: "/",
    ProductDetailPage: "/product",
    ShopDetailPage: "/shop",
    SearchProductPage: "/search",
    CartPage: "/cart",
    PaymentPage: "/payment",
    NotFoundPage: "/not-found",
    UnderDevPage: "/under-dev",
    CategoryProductPage: "/category",
    ProfilePage: "/profile",
    ViewOrdersPage: "/view-orders",
    EditAddressDeliverPage: "/address-deliver",
    ChangePasswordPage: "/change-password",
    SignInPage: "/sign-in",
    SignUpPage: "/sign-up",
    AddColumnPage: "/add-column"
  },
  seller: {
    Home: "/",
    Root: "/seller",
    SignInPage: "/sign-in",
    TransactionPage: "/seller/transaction",
    ProductPage: "/seller/product",
    AddProductPage: "/seller/product/add",
    CreateVoucherPage: "/seller/voucher/create",
    PerformancePage: "/seller/performance",
    ShopReviewsPage: "/seller/shop-management/review",
    ShopProfilePage: "/seller/shop-management/profile",
    CatalogShopPage: "/seller/shop-management/catalog",
    ShopSetupPage: "/seller/setting",
    NotFoundPage: "/not-found",
  },
  admin: {
    Root: "/admin",
    UserPage: "/admin/account",
    CategoryPage: "/admin/category",
    ShopPage: "/admin/shop",
    VoucherPage: "/admin/shop/voucher",
    TransactionPage: "/admin/transaction",
    SignInPage: "/sign-in",
  },
};
